/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iniciosesion.gui;

import iniciosesion.dto.Usuario;
import iniciosesion.logica.LogicaUsuarios;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class Formulario extends javax.swing.JDialog {

    PantallaPrincipal pantallaPrincipal;
    String trato;
    String ruta;

    /**
     * Creates new form Formulario
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;
        initComponents();

        buttonGroupTrato.add(jRadioButtonSr);
        buttonGroupTrato.add(jRadioButtonSra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTrato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldusuario = new javax.swing.JTextField();
        jLabelContrasena = new javax.swing.JLabel();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jLabelContrasena2 = new javax.swing.JLabel();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();
        jLabelEdad = new javax.swing.JLabel();
        jSpinnerEdad = new javax.swing.JSpinner();
        jLabelLugarNacimiento = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFechaRegistro = new javax.swing.JLabel();
        jButtonImagen = new javax.swing.JButton();
        jLabelFechaRegistro1 = new javax.swing.JLabel();
        jDateChooserRegistro = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabelTrato = new javax.swing.JLabel();
        jRadioButtonSr = new javax.swing.JRadioButton();
        jRadioButtonSra = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxTerminosCondiciones = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCerrar);

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabelUsuario.setText("Usuario");
        jPanel2.add(jLabelUsuario);

        jTextFieldusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldusuario);

        jLabelContrasena.setText("Contraseña");
        jPanel2.add(jLabelContrasena);

        jPasswordFieldContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContrasenaActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordFieldContrasena);

        jLabelContrasena2.setText("Repite contraseña");
        jPanel2.add(jLabelContrasena2);

        jPasswordFieldContrasena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContrasena2ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordFieldContrasena2);

        jLabelEdad.setText("Edad");
        jPanel2.add(jLabelEdad);

        jSpinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerEdad);

        jLabelLugarNacimiento.setText("Lugar de Nacimiento");
        jPanel2.add(jLabelLugarNacimiento);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZARAGOZA", "HUESCA", "TERUEL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);

        jLabelFechaRegistro.setText("Imagen");
        jPanel2.add(jLabelFechaRegistro);

        jButtonImagen.setText("Cargar imagen");
        jButtonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagenActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonImagen);

        jLabelFechaRegistro1.setText("Fecha de Registro");
        jPanel2.add(jLabelFechaRegistro1);
        jPanel2.add(jDateChooserRegistro);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jLabelTrato.setText("Trato deseado");
        jPanel3.add(jLabelTrato);

        jRadioButtonSr.setText("Sr.");
        jRadioButtonSr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSrActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButtonSr);

        jRadioButtonSra.setText("Sra.");
        jRadioButtonSra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSraActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButtonSra);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jCheckBoxTerminosCondiciones.setText("Aceptar Terminos y Condiciones.");
        jCheckBoxTerminosCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTerminosCondicionesActionPerformed(evt);
            }
        });

        jButton1.setText("¿Necesitas ayuda?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxTerminosCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTerminosCondiciones))
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void prueba(){
        
    }
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here: 
        String user = jTextFieldusuario.getText();
        String contrasena = new String(jPasswordFieldContrasena.getPassword());
        String contrasena2 = new String(jPasswordFieldContrasena2.getPassword());
        int edad = (Integer) jSpinnerEdad.getValue();
        String lugarNacimiento = (String) jComboBox1.getSelectedItem();
        Date fechaRegistro = jDateChooserRegistro.getDate(); // Asume que `fechaRegistro` es tipo `Date`
        String trato = this.trato; // Sr. o Sra.

        if (!contrasena.equals(contrasena2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Por favor, verifique.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (user.equals("")) {
            JOptionPane.showMessageDialog(this, "No puedes dejar vacío el usuario", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (contrasena.equals("")) {
            JOptionPane.showMessageDialog(this, "No puedes dejar vacía la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (fechaRegistro == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una fecha de registro", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!jCheckBoxTerminosCondiciones.isSelected()) {
            JOptionPane.showMessageDialog(this, "Tienes que aceptar los términos y condiciones para poder continuar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (trato == null) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar un trato", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int respuestaRegistro = JOptionPane.showConfirmDialog(this, "¿Esta seguro de que quiere registrar el usuario?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuestaRegistro != JOptionPane.YES_OPTION) {
                return;
            }
            Usuario usuario = new Usuario(trato, user, contrasena, contrasena2, edad, lugarNacimiento, ruta, fechaRegistro.toString());
            LogicaUsuarios.anadirUsuario(usuario);
            setVisible(false);
        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldusuarioActionPerformed

    private void jPasswordFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasenaActionPerformed

    private void jRadioButtonSrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSrActionPerformed
        // TODO add your handling code here:
        trato = "Sr.";
    }//GEN-LAST:event_jRadioButtonSrActionPerformed

    private void jPasswordFieldContrasena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasena2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBoxTerminosCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTerminosCondicionesActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxTerminosCondiciones.isSelected()) {
            // Si la casilla es seleccionada, mostrar el mensaje de confirmación
            int response = JOptionPane.showConfirmDialog(this, "¿Acepta los términos y condiciones?", "Confirmación", JOptionPane.YES_NO_OPTION);

            // Si el usuario selecciona "No", desmarcar la casilla
            if (response != JOptionPane.YES_OPTION) {
                jCheckBoxTerminosCondiciones.setSelected(false);
            }
        }

    }//GEN-LAST:event_jCheckBoxTerminosCondicionesActionPerformed

    private void jRadioButtonSraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSraActionPerformed
        // TODO add your handling code here:
        trato = "Sra.";
    }//GEN-LAST:event_jRadioButtonSraActionPerformed

    private void jButtonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == 0) {
            ruta = fileChooser.getSelectedFile().getPath();
        }
    }//GEN-LAST:event_jButtonImagenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Para registrarse, complete todos los campos y asegúrese de que las contraseñas coincidan. No se olvide de aceptar los términos y condiciones.", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonImagen;
    private javax.swing.JCheckBox jCheckBoxTerminosCondiciones;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooserRegistro;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelContrasena2;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFechaRegistro;
    private javax.swing.JLabel jLabelFechaRegistro1;
    private javax.swing.JLabel jLabelLugarNacimiento;
    private javax.swing.JLabel jLabelTrato;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JRadioButton jRadioButtonSr;
    private javax.swing.JRadioButton jRadioButtonSra;
    private javax.swing.JSpinner jSpinnerEdad;
    private javax.swing.JTextField jTextFieldusuario;
    // End of variables declaration//GEN-END:variables
}
